### ISSUE TITLE
shell self-assessment and refresher quiz

### ISSUE THREAD

**Issue by qiwang7** [cambiotraining/hpc-intro#8]
I compiled those for the shell workshop I run, as homework:
https://wiki.cam.ac.uk/plantsci-bioinfo/Shell_quiz

Most of them are taken from data carpentry material anyway. Maybe a subset can be used for shell self-assessment and refresher material, before the HPC workshop.

**Comment by tavareshugo** [comment]
Thanks! 
Maybe some of these could be added to the "Extras" and sent to the attendees before the course.

**Comment by tavareshugo** [comment]
We now have a self-assessment quiz that we send to participants before each workshop.
